In [1]:
%use dataframe(v=1.0.0-Beta3n)

In [2]:
dataFrameConfig.version

1.0.0-Beta3n

In [5]:
val df = DataFrame.readCsv("../../../../data/books.csv")

df

id,title,author_id,author_firstName,author_lastName,genre,publisher
1,Little Hands Clapping,4,Meaghan,Haag,Crime/Detective,Emerald Group Publishing
2,All the King's Men,4,Ali,Leuschke,Biography/Autobiography,Penguin Books
3,Tiger! Tiger!,59,Honey,Beahan,Essay,Borgo Press
4,Recalled to Life,67,Alden,Nolan,Horror,Vintage Books
5,The Parliament of Man,63,Quincy,Wisoky,Fiction in verse,Mark Batty Publisher
6,Have His Carcase,40,Toby,Rath,Fable,Shambhala Publications
7,I Sing the Body Electric,3,Garret,Bradtke,Mythology,Liberty Fund
8,His Dark Materials,23,Venessa,Wolf,Mythology,Gay Men's Press
9,If I Forget Thee Jerusalem,26,Russell,Weber,Mythology,Vintage Books at Random House
10,Frequent Hearses,30,Stephan,Tremblay,Metafiction,Ladybird Books
11,"Those Barren Leaves, Thrones, Dominat...",3,Eartha,Cummings,Mystery,Darakwon Press
12,Lilies of the Field,42,Brianne,Pfeffer,Western,Taylor & Francis
13,Jacob Have I Loved,42,Rhett,McLaughlin,Narrative nonfiction,Orchard Books
14,The Far-Distant Oxus,4,Lauretta,Parisian,Narrative nonfiction,New Directions Publishing
15,If I Forget Thee Jerusalem,23,Angelo,Leannon,Comic/Graphic Novel,Nauka
16,Time of our Darkness,36,Mark,Reichert,Narrative nonfiction,Pathfinder Press
17,An Evil Cradling,22,Forest,Tromp,Folklore,Hackett Publishing Company
18,Fame Is the Spur,2,Thanh,Huels,Science fiction,Chick Publications
19,The Line of Beauty,57,Eugenio,Deckow,Fanfiction,Kessinger Publishing
20,Bury My Heart at Wounded Knee,93,Setsuko,Cormier,Horror,Marshall Cavendish

In [24]:
df.schema()

id: Int
firstName: String
lastName: String
address: String
email: String

In [25]:
df.describe()

name,type,count,unique,nulls,top,freq,mean,std,min,p25,median,p75,max
id,Int,50000,50000,0,1,1,25000.500000,14433.901067,1,12500.416667,25000.500000,37500.583333,50000
firstName,String,50000,5155,0,Clair,41,null,null,Aaron,Dominic,Julian,Particia,Zulma
lastName,String,50000,473,0,Nikolaus,135,null,null,Abbott,Fritsch,Kuvalis,Rohan,Zulauf
address,String,50000,50000,0,"Apt. 710 2632 Powlowski Harbors, Sout...",1,null,null,"000 Avis Hill, Joneschester, OR 16348","5083 Pok Loaf, West Izetta, NH 00435","99737 Darla Parkways, North Bertrammo...","Suite 103 393 Chieko Center, Jaymesta...","Suite 999 9820 Miquel Drive, East Rus..."
email,String,50000,49759,0,doug.hegmann@gmail.com,3,null,null,aaron.bailey@hotmail.com,domenic.thiel@yahoo.com,justina.friesen@yahoo.com,patrick.veum@hotmail.com,zulma.spencer@gmail.com

In [29]:
df.values().last()

isabel.schultz@hotmail.com

In [33]:
df.singleOrNull { lastName == "Hane" && address.contains("Odell Village") }

id,firstName,lastName,address,email
13,Drew,Hane,"369 Odell Village, Lake Johnathon, MD...",anjanette.spencer@hotmail.com

In [37]:
df.select { firstName and lastName }

firstName,lastName
Chau,Stokes
Numbers,Bergstrom
Alena,Beahan
Sparkle,Hodkiewicz
Stan,Quitzon
Ronald,Stehr
Usha,Blick
Nick,Keeling
Quentin,Kub
Lorean,Bosco
Chasity,Auer
Hertha,Harvey
Drew,Hane
Vernie,Bednar
Marcellus,Deckow
Lyman,Runolfsdottir
Rhett,Rogahn
Zella,Kassulke
Lance,Schroeder
Elfriede,Kunze

In [38]:
val dfWithGroup = df.group { firstName and lastName }.into { "name" }

dfWithGroup

id,name,,address,email
,firstName,lastName,,
1,Chau,Stokes,"Apt. 710 2632 Powlowski Harbors, Sout...",halley.jenkins@gmail.com
2,Numbers,Bergstrom,"Suite 468 164 Hessel Ferry, South Moz...",susanna.schiller@hotmail.com
3,Alena,Beahan,"743 Filiberto Park, Jifurt, KS 39252",tanja.oberbrunner@gmail.com
4,Sparkle,Hodkiewicz,"Suite 692 95974 Sawayn Course, New Ty...",lina.oconnell@yahoo.com
5,Stan,Quitzon,"65722 Romana Ferry, Mirellaburgh, IL ...",patrick.brakus@yahoo.com
6,Ronald,Stehr,"45890 Rodriguez Forks, North Karleen,...",casey.greenholt@yahoo.com
7,Usha,Blick,"Apt. 785 6641 Anglea Pines, North Ran...",larraine.treutel@yahoo.com
8,Nick,Keeling,"248 Ortiz Skyway, East Rayfordton, SD...",gene.grimes@hotmail.com
9,Quentin,Kub,"588 Harold Shore, New Elroyborough, C...",giuseppe.batz@hotmail.com
10,Lorean,Bosco,"Apt. 692 23594 Jaskolski Street, Port...",ward.kiehn@hotmail.com
11,Chasity,Auer,"132 Jones Knolls, Lake Rudyview, AR 8...",lesley.herman@gmail.com
12,Hertha,Harvey,"Suite 717 01503 Clifford Wells, Reich...",chana.dickinson@gmail.com
13,Drew,Hane,"369 Odell Village, Lake Johnathon, MD...",anjanette.spencer@hotmail.com
14,Vernie,Bednar,"745 Loren Path, Gingerchester, NC 83148",penny.borer@yahoo.com
15,Marcellus,Deckow,"Apt. 771 36597 Emogene Greens, North ...",elizebeth.jast@hotmail.com
16,Lyman,Runolfsdottir,"27801 Shad Haven, Columbusbury, ID 41438",ivan.wolff@yahoo.com
17,Rhett,Rogahn,"Suite 308 2873 Legros Key, Ankundingt...",elenora.dibbert@yahoo.com
18,Zella,Kassulke,"Apt. 906 356 Carroll Radial, Cathysid...",alvina.kreiger@yahoo.com
19,Lance,Schroeder,"8709 Brown Key, Isiahbury, MI 45565",scotty.hettinger@gmail.com
20,Elfriede,Kunze,"Suite 722 17918 Willow Fork, West Asa...",jacelyn.flatley@gmail.com

In [40]:
dfWithGroup.flatten()

id,firstName,lastName,address,email
1,Chau,Stokes,"Apt. 710 2632 Powlowski Harbors, Sout...",halley.jenkins@gmail.com
2,Numbers,Bergstrom,"Suite 468 164 Hessel Ferry, South Moz...",susanna.schiller@hotmail.com
3,Alena,Beahan,"743 Filiberto Park, Jifurt, KS 39252",tanja.oberbrunner@gmail.com
4,Sparkle,Hodkiewicz,"Suite 692 95974 Sawayn Course, New Ty...",lina.oconnell@yahoo.com
5,Stan,Quitzon,"65722 Romana Ferry, Mirellaburgh, IL ...",patrick.brakus@yahoo.com
6,Ronald,Stehr,"45890 Rodriguez Forks, North Karleen,...",casey.greenholt@yahoo.com
7,Usha,Blick,"Apt. 785 6641 Anglea Pines, North Ran...",larraine.treutel@yahoo.com
8,Nick,Keeling,"248 Ortiz Skyway, East Rayfordton, SD...",gene.grimes@hotmail.com
9,Quentin,Kub,"588 Harold Shore, New Elroyborough, C...",giuseppe.batz@hotmail.com
10,Lorean,Bosco,"Apt. 692 23594 Jaskolski Street, Port...",ward.kiehn@hotmail.com
11,Chasity,Auer,"132 Jones Knolls, Lake Rudyview, AR 8...",lesley.herman@gmail.com
12,Hertha,Harvey,"Suite 717 01503 Clifford Wells, Reich...",chana.dickinson@gmail.com
13,Drew,Hane,"369 Odell Village, Lake Johnathon, MD...",anjanette.spencer@hotmail.com
14,Vernie,Bednar,"745 Loren Path, Gingerchester, NC 83148",penny.borer@yahoo.com
15,Marcellus,Deckow,"Apt. 771 36597 Emogene Greens, North ...",elizebeth.jast@hotmail.com
16,Lyman,Runolfsdottir,"27801 Shad Haven, Columbusbury, ID 41438",ivan.wolff@yahoo.com
17,Rhett,Rogahn,"Suite 308 2873 Legros Key, Ankundingt...",elenora.dibbert@yahoo.com
18,Zella,Kassulke,"Apt. 906 356 Carroll Radial, Cathysid...",alvina.kreiger@yahoo.com
19,Lance,Schroeder,"8709 Brown Key, Isiahbury, MI 45565",scotty.hettinger@gmail.com
20,Elfriede,Kunze,"Suite 722 17918 Willow Fork, West Asa...",jacelyn.flatley@gmail.com

In [39]:
@DataSchema
interface Person {
    val id: Int
    val firstName: String
    val lastName: String
    val address: String
    val email: String
}

df.cast<Person>()

id,firstName,lastName,address,email
1,Chau,Stokes,"Apt. 710 2632 Powlowski Harbors, Sout...",halley.jenkins@gmail.com
2,Numbers,Bergstrom,"Suite 468 164 Hessel Ferry, South Moz...",susanna.schiller@hotmail.com
3,Alena,Beahan,"743 Filiberto Park, Jifurt, KS 39252",tanja.oberbrunner@gmail.com
4,Sparkle,Hodkiewicz,"Suite 692 95974 Sawayn Course, New Ty...",lina.oconnell@yahoo.com
5,Stan,Quitzon,"65722 Romana Ferry, Mirellaburgh, IL ...",patrick.brakus@yahoo.com
6,Ronald,Stehr,"45890 Rodriguez Forks, North Karleen,...",casey.greenholt@yahoo.com
7,Usha,Blick,"Apt. 785 6641 Anglea Pines, North Ran...",larraine.treutel@yahoo.com
8,Nick,Keeling,"248 Ortiz Skyway, East Rayfordton, SD...",gene.grimes@hotmail.com
9,Quentin,Kub,"588 Harold Shore, New Elroyborough, C...",giuseppe.batz@hotmail.com
10,Lorean,Bosco,"Apt. 692 23594 Jaskolski Street, Port...",ward.kiehn@hotmail.com
11,Chasity,Auer,"132 Jones Knolls, Lake Rudyview, AR 8...",lesley.herman@gmail.com
12,Hertha,Harvey,"Suite 717 01503 Clifford Wells, Reich...",chana.dickinson@gmail.com
13,Drew,Hane,"369 Odell Village, Lake Johnathon, MD...",anjanette.spencer@hotmail.com
14,Vernie,Bednar,"745 Loren Path, Gingerchester, NC 83148",penny.borer@yahoo.com
15,Marcellus,Deckow,"Apt. 771 36597 Emogene Greens, North ...",elizebeth.jast@hotmail.com
16,Lyman,Runolfsdottir,"27801 Shad Haven, Columbusbury, ID 41438",ivan.wolff@yahoo.com
17,Rhett,Rogahn,"Suite 308 2873 Legros Key, Ankundingt...",elenora.dibbert@yahoo.com
18,Zella,Kassulke,"Apt. 906 356 Carroll Radial, Cathysid...",alvina.kreiger@yahoo.com
19,Lance,Schroeder,"8709 Brown Key, Isiahbury, MI 45565",scotty.hettinger@gmail.com
20,Elfriede,Kunze,"Suite 722 17918 Willow Fork, West Asa...",jacelyn.flatley@gmail.com