In [1]:
%use dataframe(v=1.0.0-Beta3n)

In [2]:
dataFrameConfig.version

1.0.0-Beta3n

In [4]:
val df = DataFrame.readJson("../../../../data/books.json")

df

id,title,author_id,author_firstName,author_lastName,genre,publisher
1,That Hideous Strength,11,Renaldo,Greenfelder,Mythopoeia,Gefen Publishing House
2,The Way Through the Woods,94,Jimmy,Graham,Humor,Ellora's Cave
3,The Mermaids Singing,47,Christa,Hane,Textbook,Boydell & Brewer
4,What's Become of Waring,3,Eveline,Ullrich,Humor,Pan Books
5,"Absalom, Absalom!",11,Darin,Hane,Science fiction,Boydell & Brewer
6,To Sail Beyond the Sunset,62,Bret,Jacobs,Textbook,Atlantic Books
7,In Dubious Battle,22,Jackson,Hegmann,Fantasy,Breslov Research Institute
8,The Way Through the Woods,42,Vivienne,Streich,Fantasy,BBC Books
9,Ring of Bright Water,44,Gina,Volkman,Mystery,Karadi Tales
10,Consider Phlebas,62,Tara,Swift,Tall tale,Boydell & Brewer
11,Infinite Jest,30,Joni,Jaskolski,Horror,Addison-Wesley
12,Cabbages and Kings,95,Georgia,Beier,Narrative nonfiction,Hodder & Stoughton
13,Stranger in a Strange Land,6,Willis,Torphy,Biography/Autobiography,Kogan Page
14,The Other Side of Silence,46,Barb,Reynolds,Horror,Broadview Press
15,Carrion Comfort,61,Isiah,Kreiger,Suspense/Thriller,Chronicle Books
16,Consider Phlebas,74,Tracey,Rau,Crime/Detective,Matthias Media
17,To Say Nothing of the Dog,47,Tessie,Mohr,Essay,Open University Press
18,A Scanner Darkly,84,Leana,Schaefer,Western,Carlton Books
19,Little Hands Clapping,65,Katy,Konopelski,Mythology,University of Minnesota Press
20,Brandy of the Damned,63,Pearlene,Schmeler,Tall tale,Pen and Sword Books

In [6]:
val dfFirstHalf = df[0..24_999]

dfFirstHalf

id,firstName,lastName,address,email
1,Chau,Stokes,"Apt. 710 2632 Powlowski Harbors, Sout...",halley.jenkins@gmail.com
2,Numbers,Bergstrom,"Suite 468 164 Hessel Ferry, South Moz...",susanna.schiller@hotmail.com
3,Alena,Beahan,"743 Filiberto Park, Jifurt, KS 39252",tanja.oberbrunner@gmail.com
4,Sparkle,Hodkiewicz,"Suite 692 95974 Sawayn Course, New Ty...",lina.oconnell@yahoo.com
5,Stan,Quitzon,"65722 Romana Ferry, Mirellaburgh, IL ...",patrick.brakus@yahoo.com
6,Ronald,Stehr,"45890 Rodriguez Forks, North Karleen,...",casey.greenholt@yahoo.com
7,Usha,Blick,"Apt. 785 6641 Anglea Pines, North Ran...",larraine.treutel@yahoo.com
8,Nick,Keeling,"248 Ortiz Skyway, East Rayfordton, SD...",gene.grimes@hotmail.com
9,Quentin,Kub,"588 Harold Shore, New Elroyborough, C...",giuseppe.batz@hotmail.com
10,Lorean,Bosco,"Apt. 692 23594 Jaskolski Street, Port...",ward.kiehn@hotmail.com
11,Chasity,Auer,"132 Jones Knolls, Lake Rudyview, AR 8...",lesley.herman@gmail.com
12,Hertha,Harvey,"Suite 717 01503 Clifford Wells, Reich...",chana.dickinson@gmail.com
13,Drew,Hane,"369 Odell Village, Lake Johnathon, MD...",anjanette.spencer@hotmail.com
14,Vernie,Bednar,"745 Loren Path, Gingerchester, NC 83148",penny.borer@yahoo.com
15,Marcellus,Deckow,"Apt. 771 36597 Emogene Greens, North ...",elizebeth.jast@hotmail.com
16,Lyman,Runolfsdottir,"27801 Shad Haven, Columbusbury, ID 41438",ivan.wolff@yahoo.com
17,Rhett,Rogahn,"Suite 308 2873 Legros Key, Ankundingt...",elenora.dibbert@yahoo.com
18,Zella,Kassulke,"Apt. 906 356 Carroll Radial, Cathysid...",alvina.kreiger@yahoo.com
19,Lance,Schroeder,"8709 Brown Key, Isiahbury, MI 45565",scotty.hettinger@gmail.com
20,Elfriede,Kunze,"Suite 722 17918 Willow Fork, West Asa...",jacelyn.flatley@gmail.com

In [7]:
val dfSecondHalf = df[25_000..49_999]

dfSecondHalf

id,firstName,lastName,address,email
25001,Irish,Reynolds,"Apt. 222 76574 Jody Island, Port Weld...",josue.labadie@yahoo.com
25002,Alba,Torp,"00688 Andrea Course, Miside, NJ 13304",paul.stiedemann@hotmail.com
25003,Jake,Runte,"69848 Malik Neck, North Jesusita, HI ...",lucien.fisher@gmail.com
25004,Bernardo,Veum,"Apt. 572 62325 Wisozk Crossroad, Lake...",norberto.wilkinson@gmail.com
25005,Garret,Macejkovic,"166 Jacobi Camp, Lake Arden, LA 07948",barbar.graham@gmail.com
25006,Juliann,Greenfelder,"810 Blick Lane, Rathborough, HI 05278",fritz.grady@gmail.com
25007,Clifford,Ortiz,"Apt. 984 775 Shon Ferry, Schadenstad,...",joseph.upton@gmail.com
25008,Amy,Moore,"64195 Flatley Circles, Lanoraton, MA ...",lavenia.blanda@hotmail.com
25009,Rocco,Yundt,"Suite 183 4160 Viva Way, Osvaldofort,...",shelton.greenfelder@gmail.com
25010,Geraldo,Hartmann,"Suite 903 516 Osinski Brooks, Port Jo...",rodger.skiles@gmail.com
25011,Leo,VonRueden,"67500 Schowalter Canyon, North Enoch,...",tyson.auer@yahoo.com
25012,Therese,Considine,"Apt. 660 204 Krystle Station, Beervie...",jonelle.kemmer@hotmail.com
25013,Taylor,Labadie,"031 Dave Centers, Jerdehaven, MD 62163",dante.howe@hotmail.com
25014,Virgil,Trantow,"686 Landon Burg, West Marindahaven, N...",jessi.farrell@yahoo.com
25015,Shantelle,Quitzon,"758 Prosacco Lakes, Port Teofilashire...",porter.schultz@gmail.com
25016,Doyle,Donnelly,"294 Hilton Course, New Justaville, UT...",ray.huels@gmail.com
25017,Zora,Larkin,"40021 Ritchie Track, Port Fabian, IA ...",coralee.mraz@yahoo.com
25018,Bradly,Little,"95437 Miller Plaza, Port Doretha, KY ...",cleora.legros@hotmail.com
25019,Carlota,Bechtelar,"1599 Jenkins Knoll, Maddieborough, WY...",lon.harber@yahoo.com
25020,Brady,Erdman,"1417 Durgan Point, North Neville, MA ...",donald.powlowski@hotmail.com

In [8]:
val dfConcat = dfFirstHalf.concat(dfSecondHalf)

dfConcat

id,firstName,lastName,address,email
1,Chau,Stokes,"Apt. 710 2632 Powlowski Harbors, Sout...",halley.jenkins@gmail.com
2,Numbers,Bergstrom,"Suite 468 164 Hessel Ferry, South Moz...",susanna.schiller@hotmail.com
3,Alena,Beahan,"743 Filiberto Park, Jifurt, KS 39252",tanja.oberbrunner@gmail.com
4,Sparkle,Hodkiewicz,"Suite 692 95974 Sawayn Course, New Ty...",lina.oconnell@yahoo.com
5,Stan,Quitzon,"65722 Romana Ferry, Mirellaburgh, IL ...",patrick.brakus@yahoo.com
6,Ronald,Stehr,"45890 Rodriguez Forks, North Karleen,...",casey.greenholt@yahoo.com
7,Usha,Blick,"Apt. 785 6641 Anglea Pines, North Ran...",larraine.treutel@yahoo.com
8,Nick,Keeling,"248 Ortiz Skyway, East Rayfordton, SD...",gene.grimes@hotmail.com
9,Quentin,Kub,"588 Harold Shore, New Elroyborough, C...",giuseppe.batz@hotmail.com
10,Lorean,Bosco,"Apt. 692 23594 Jaskolski Street, Port...",ward.kiehn@hotmail.com
11,Chasity,Auer,"132 Jones Knolls, Lake Rudyview, AR 8...",lesley.herman@gmail.com
12,Hertha,Harvey,"Suite 717 01503 Clifford Wells, Reich...",chana.dickinson@gmail.com
13,Drew,Hane,"369 Odell Village, Lake Johnathon, MD...",anjanette.spencer@hotmail.com
14,Vernie,Bednar,"745 Loren Path, Gingerchester, NC 83148",penny.borer@yahoo.com
15,Marcellus,Deckow,"Apt. 771 36597 Emogene Greens, North ...",elizebeth.jast@hotmail.com
16,Lyman,Runolfsdottir,"27801 Shad Haven, Columbusbury, ID 41438",ivan.wolff@yahoo.com
17,Rhett,Rogahn,"Suite 308 2873 Legros Key, Ankundingt...",elenora.dibbert@yahoo.com
18,Zella,Kassulke,"Apt. 906 356 Carroll Radial, Cathysid...",alvina.kreiger@yahoo.com
19,Lance,Schroeder,"8709 Brown Key, Isiahbury, MI 45565",scotty.hettinger@gmail.com
20,Elfriede,Kunze,"Suite 722 17918 Willow Fork, West Asa...",jacelyn.flatley@gmail.com

In [9]:
dfConcat.convert { lastName }.with { it.uppercase() }

id,firstName,lastName,address,email
1,Chau,STOKES,"Apt. 710 2632 Powlowski Harbors, Sout...",halley.jenkins@gmail.com
2,Numbers,BERGSTROM,"Suite 468 164 Hessel Ferry, South Moz...",susanna.schiller@hotmail.com
3,Alena,BEAHAN,"743 Filiberto Park, Jifurt, KS 39252",tanja.oberbrunner@gmail.com
4,Sparkle,HODKIEWICZ,"Suite 692 95974 Sawayn Course, New Ty...",lina.oconnell@yahoo.com
5,Stan,QUITZON,"65722 Romana Ferry, Mirellaburgh, IL ...",patrick.brakus@yahoo.com
6,Ronald,STEHR,"45890 Rodriguez Forks, North Karleen,...",casey.greenholt@yahoo.com
7,Usha,BLICK,"Apt. 785 6641 Anglea Pines, North Ran...",larraine.treutel@yahoo.com
8,Nick,KEELING,"248 Ortiz Skyway, East Rayfordton, SD...",gene.grimes@hotmail.com
9,Quentin,KUB,"588 Harold Shore, New Elroyborough, C...",giuseppe.batz@hotmail.com
10,Lorean,BOSCO,"Apt. 692 23594 Jaskolski Street, Port...",ward.kiehn@hotmail.com
11,Chasity,AUER,"132 Jones Knolls, Lake Rudyview, AR 8...",lesley.herman@gmail.com
12,Hertha,HARVEY,"Suite 717 01503 Clifford Wells, Reich...",chana.dickinson@gmail.com
13,Drew,HANE,"369 Odell Village, Lake Johnathon, MD...",anjanette.spencer@hotmail.com
14,Vernie,BEDNAR,"745 Loren Path, Gingerchester, NC 83148",penny.borer@yahoo.com
15,Marcellus,DECKOW,"Apt. 771 36597 Emogene Greens, North ...",elizebeth.jast@hotmail.com
16,Lyman,RUNOLFSDOTTIR,"27801 Shad Haven, Columbusbury, ID 41438",ivan.wolff@yahoo.com
17,Rhett,ROGAHN,"Suite 308 2873 Legros Key, Ankundingt...",elenora.dibbert@yahoo.com
18,Zella,KASSULKE,"Apt. 906 356 Carroll Radial, Cathysid...",alvina.kreiger@yahoo.com
19,Lance,SCHROEDER,"8709 Brown Key, Isiahbury, MI 45565",scotty.hettinger@gmail.com
20,Elfriede,KUNZE,"Suite 722 17918 Willow Fork, West Asa...",jacelyn.flatley@gmail.com

In [10]:
dfConcat.filter { address.contains("NY") }

id,firstName,lastName,address,email
21,Carroll,Wilkinson,"3137 Price Knolls, Jeraldineberg, NY ...",tammera.morissette@gmail.com
38,Susannah,Berge,"8540 Kohler Lodge, Breitenbergport, N...",ron.greenholt@yahoo.com
94,Thanh,Morar,"93858 Carson Walks, Lake Sibyl, NY 37772",setsuko.cummerata@gmail.com
112,Tyrell,Koepp,"70289 Dayna Islands, East Dulcie, NY ...",bennie.stroman@gmail.com
283,Geraldo,Pagac,"Suite 763 7053 Brekke Court, Padbergb...",inez.prohaska@yahoo.com
310,Margareta,Yundt,"Apt. 734 42138 Kaitlyn Ramp, Swiftbur...",aubrey.dubuque@yahoo.com
337,Lawerence,Kassulke,"1114 Kerluke Crest, Parismouth, NY 14411",bari.kuhn@gmail.com
410,Delma,Lesch,"Apt. 713 474 Turner Unions, East Rexl...",lenard.cartwright@gmail.com
472,Dixie,Purdy,"Apt. 638 0794 Landon Tunnel, Port Zac...",ayako.mayer@yahoo.com
716,Elwood,Connelly,"3146 Berna Hills, West Lara, NY 45506",chassidy.doyle@yahoo.com
882,Sheldon,Ledner,"Apt. 498 89473 Lue Corners, Volkmanfo...",stephine.kris@yahoo.com
908,Mary,Carter,"Apt. 733 817 Homenick Underpass, Port...",deandra.treutel@gmail.com
934,Lorean,Torp,"Apt. 968 41019 Hana Harbor, MacGyverp...",winford.pagac@gmail.com
962,Elna,Klocko,"Apt. 182 151 Patricia Spur, Quigleybu...",mandie.nader@yahoo.com
995,Lauralee,Turcotte,"277 Richard Walk, North Marlinstad, N...",lilly.schmeler@yahoo.com
996,Lowell,Stark,"27375 Collins Overpass, Edenbury, NY ...",azzie.dibbert@yahoo.com
1038,Lauryn,Kautzer,"Apt. 585 799 Gottlieb Crossroad, Lake...",jesus.lakin@gmail.com
1099,Willie,Langosh,"403 Sergio Viaduct, Lake Ken, NY 99108",rosia.jenkins@gmail.com
1262,Chauncey,Nitzsche,"Suite 969 017 Sandee Corner, Runtesta...",beaulah.morar@yahoo.com
1301,Tinisha,Bergstrom,"94661 Hermelinda Lane, Effertzburgh, ...",german.batz@yahoo.com

In [11]:
dfConcat.count { firstName == "Carroll" }

30

In [13]:
val grouped = df.groupBy { firstName }

grouped

In [17]:
grouped.sortBy { firstName }