Setup

In [17]:
USE {
    dependencies("org.postgresql:postgresql:42.7.8")
}

In [18]:
%use dataframe(1.0.0-Beta3n)

In [19]:
dataFrameConfig.version

1.0.0-Beta3n

In [20]:
val dbConfig = DbConnectionConfig("jdbc:postgresql://localhost:5432/test_db", "test_user", "test")

Reading tables

In [21]:
val customers = DataFrame.readSqlTable(dbConfig, "customers")

customers

id,firstname,lastname,address,email
1,Ernie,Abshire,"Apt. 922 8432 Lebsack Rest, Lake Euge...",antonio.spinka@yahoo.com
2,Kazuko,Sauer,"Suite 662 3602 Vandervort Rapid, Sout...",candace.haag@yahoo.com
3,Irving,Simonis,"Apt. 340 4533 Gerlach Prairie, Lake W...",leeann.towne@yahoo.com
4,Bennett,Conroy,"Suite 364 106 Jast Port, Bennietown, ...",hai.koss@yahoo.com
5,Ladonna,Dicki,"5779 Bula Inlet, Criststad, NJ 53400",gabriel.rath@hotmail.com
6,Myrl,Kessler,"491 Jordan Ferry, South Violastad, ID...",keith.dooley@hotmail.com
7,Angelo,Lebsack,"053 Daniella Common, Boganburgh, SD 6...",amina.ortiz@hotmail.com
8,Adriane,Terry,"Suite 387 7127 Daugherty Plaza, Koepp...",matha.lynch@yahoo.com
9,Jolynn,Braun,"Suite 952 886 Flora Parkways, Lake Sc...",lexie.terry@hotmail.com
10,Flavia,Spencer,"04091 Clarinda Loaf, Lake Tienfurt, K...",leia.gerlach@hotmail.com
11,Velvet,Bradtke,"Suite 221 96745 Carmelo Trafficway, E...",audria.dickens@hotmail.com
12,Loyd,Erdman,"45999 Jesusita Via, Port Shaun, IN 41582",eloise.mraz@gmail.com
13,Mittie,Kreiger,"816 Debrah Extension, South Divinashi...",paris.cassin@gmail.com
14,Gus,Connelly,"Apt. 507 954 Phillis Cliff, Port Ross...",yelena.kessler@yahoo.com
15,Manda,Jast,"401 Tremblay Court, Alaneview, IN 53572",shirl.frami@hotmail.com
16,Marquerite,Stanton,"474 Dibbert Lodge, South Warren, DE 8...",sara.renner@yahoo.com
17,Ricky,Greenholt,"Apt. 901 030 Leisha Courts, Walshhave...",foster.von@hotmail.com
18,Jason,Powlowski,"Suite 847 3238 Doug Flat, Uptonboroug...",michal.huels@hotmail.com
19,Stan,Hammes,"Suite 704 06129 Lemke Forest, Port La...",antwan.bailey@hotmail.com
20,Kizzie,Koepp,"Suite 524 57867 Orlando Key, West Den...",georgene.corkery@gmail.com

In [22]:
val dfBrad = DataFrame.readSqlQuery(dbConfig, "SELECT * FROM customers WHERE firstname = 'Brad'")

dfBrad

id,firstname,lastname,address,email
2239,Brad,Kautzer,"454 Grady Turnpike, Lake Wiley, AL 38706",chantal.thiel@hotmail.com
9923,Brad,Braun,"75895 Roosevelt Ramp, South Mel, WV 9...",phillip.wilderman@gmail.com
12496,Brad,Medhurst,"617 Hammes Course, North Nathanshire,...",dario.bashirian@yahoo.com
19535,Brad,Krajcik,"40090 Mozell Overpass, Port Delmyton,...",cristopher.gottlieb@gmail.com
25730,Brad,Cormier,"550 Rico Valleys, Koeppview, WY 31426",davida.daniel@gmail.com
26792,Brad,DuBuque,"Apt. 424 6682 Vinita Prairie, Anderso...",mason.pollich@gmail.com
27103,Brad,Quigley,"Apt. 188 0810 Miles Orchard, South Dw...",jesse.gorczany@yahoo.com
27896,Brad,Lindgren,"Suite 810 0691 Carter Trace, West Ste...",dewayne.durgan@hotmail.com
29789,Brad,McCullough,"Suite 389 2664 Crona Mount, Baileyfor...",clair.mayer@gmail.com
30746,Brad,Haag,"Apt. 731 229 Lueilwitz Manors, Lincol...",sherika.ledner@yahoo.com
32606,Brad,Turner,"Apt. 819 0859 Royce Village, South Ge...",marion.ohara@yahoo.com
33604,Brad,Bailey,"Apt. 346 34525 King Island, Soland, I...",rey.murphy@gmail.com
34883,Brad,Volkman,"Suite 774 05379 Feeney Union, Ziemann...",britany.flatley@hotmail.com
40544,Brad,Schuppe,"041 Jacobi Parkway, Port Sanachester,...",lino.bergnaum@gmail.com
44755,Brad,O'Conner,"Apt. 202 62289 Mimi Ranch, Caryburgh,...",quinton.fisher@yahoo.com
45446,Brad,Ruecker,"Apt. 513 98225 Rippin Valley, New Bea...",meg.gleichner@hotmail.com
45531,Brad,Heller,"9462 Ray Crossing, Milfordmouth, IL 1...",catina.hahn@yahoo.com

In [23]:
val dataframes = DataFrame.readAllSqlTables(dbConfig)

dataframes

{books=    id                        title                  author                genre                    publisher
  0  1     A Swiftly Tilting Planet             Denny Block              Western    Harcourt Trade Publishers
  1  2            Rosemary Sutcliff  Mrs. Amparo Runolfsson             Textbook      Farrar, Straus & Giroux
  2  3   The Wind's Twelve Quarters        Dr. Buffy Walter               Legend                Vintage Books
  3  4             Consider Phlebas             Layla Bauch            Tall tale               Matthias Media
  4  5                  Vile Bodies       Donnette Kutch MD            Tall tale               Fairview Press
  5  6       No Country for Old Men        Catina Koepp PhD   Historical fiction           Mandrake of Oxford
  6  7    The Other Side of Silence       Zackary Hirthe IV           Mythopoeia                Black Library
  7  8    Time To Murder And Create        Erasmo Kulas Jr.              Classic               Atlantic Books
  8  9             Look to Windward                Nam Hill              Fantasy                  HarperPrism
  9 10     The Violent Bear It Away               Doug Lang                Humor           Adis International
 10 11            Nectar in a Sieve      Mrs. Lyndsay Mante             Textbook                 Viking Press
 11 12      For Whom the Bell Tolls      Vernia McKenzie II     Fiction in verse                        Brill
 12 13     Tirra Lirra by the River            Eric Hills I              Mystery         Tachyon Publications
 13 14            The Widening Gyre              Iva Durgan               Horror                    DAW Books
 14 15              In Death Ground          Dr. Ivey Fahey                Humor                Vintage Books
 15 16 Let Us Now Praise Famous Men        Rogelio Lindgren             Folklore   Athabasca University Press
 16 17               Jesting Pilate          Romona Spencer      Crime/Detective              Faber and Faber
 17 18               As I Lay Dying Cleveland Considine Sr.            Tall tale                  HarperPrism
 18 19             Of Human Bondage   Philomena Halvorson V Narrative nonfiction University of Michigan Press
 19 20       No Country for Old Men   Giovanni Kertzmann IV     Fiction in verse                  Shire Books
...
, customers=    id  firstname  lastname                                  address                      email
  0  1      Ernie   Abshire Apt. 922 8432 Lebsack Rest, Lake Euge...   antonio.spinka@yahoo.com
  1  2     Kazuko     Sauer Suite 662 3602 Vandervort Rapid, Sout...     candace.haag@yahoo.com
  2  3     Irving   Simonis Apt. 340 4533 Gerlach Prairie, Lake W...     leeann.towne@yahoo.com
  3  4    Bennett    Conroy Suite 364 106 Jast Port, Bennietown, ...         hai.koss@yahoo.com
  4  5    Ladonna     Dicki     5779 Bula Inlet, Criststad, NJ 53400   gabriel.rath@hotmail.com
  5  6       Myrl   Kessler 491 Jordan Ferry, South Violastad, ID...   keith.dooley@hotmail.com
  6  7     Angelo   Lebsack 053 Daniella Common, Boganburgh, SD 6...    amina.ortiz@hotmail.com
  7  8    Adriane     Terry Suite 387 7127 Daugherty Plaza, Koepp...      matha.lynch@yahoo.com
  8  9     Jolynn     Braun Suite 952 886 Flora Parkways, Lake Sc...    lexie.terry@hotmail.com
  9 10     Flavia   Spencer 04091 Clarinda Loaf, Lake Tienfurt, K...   leia.gerlach@hotmail.com
 10 11     Velvet   Bradtke Suite 221 96745 Carmelo Trafficway, E... audria.dickens@hotmail.com
 11 12       Loyd    Erdman 45999 Jesusita Via, Port Shaun, IN 41582      eloise.mraz@gmail.com
 12 13     Mittie   Kreiger 816 Debrah Extension, South Divinashi...     paris.cassin@gmail.com
 13 14        Gus  Connelly Apt. 507 954 Phillis Cliff, Port Ross...   yelena.kessler@yahoo.com
 14 15      Manda      Jast  401 Tremblay Court, Alaneview, IN 53572    shirl.frami@hotmail.com
 15 16 Marquerite   Stanton 474 Dibbert Lodge, South Warren, DE 8...      sara.renner@yahoo.com
 16 17      Ricky Greenholt Apt. 901 030 Leisha Courts, Walshhave...     foster.von@hotmail.com
 17 18      Jason Powlowski Suite 847 3238 Doug Flat, Uptonboroug...   michal.huels@hotmail.com
 18 19       Stan    Hammes Suite 704 06129 Lemke Forest, Port La...  antwan.bailey@hotmail.com
 19 20     Kizzie     Koepp Suite 524 57867 Orlando Key, West Den... georgene.corkery@gmail.com
...
, orders=    id customerid bookid       date quantity
  0  1      29676  47608 2025-11-20        3
  1  2      15946  22170 2025-11-20        8
  2  3      19152  41042 2025-11-20        8
  3  4       1587  39065 2025-11-20        1
  4  5      48711   7475 2025-11-20        3
  5  6      38401  44773 2025-11-20        4
  6  7      36063  25083 2025-11-20        9
  7  8      37033   5631 2025-11-20        2
  8  9      21922   5932 2025-11-20        5
  9 10      48020  42163 2025-11-20        2
 10 11      12195    840 2025-11-20        6
 11 12      27476   4873 2025-11-20        8
 12 13       5030  25148 2025-11-20        7
 13 14       4580  16468 2025-11-20        2
 14 15      21760  39783 2025-11-20        6
 15 16      33161  32489 2025-11-20        1
 16 17       9492  30000 2025-11-20        2
 17 18      28763  41973 2025-11-20        6
 18 19      45207   2259 2025-11-20        1
 19 20      34269    661 2025-11-20        8
...
}

In [24]:
dataframes.keys

[books, customers, orders]

In [25]:
val dfBooks = dataframes["books"]

dfBooks

id,title,author,genre,publisher
1,A Swiftly Tilting Planet,Denny Block,Western,Harcourt Trade Publishers
2,Rosemary Sutcliff,Mrs. Amparo Runolfsson,Textbook,"Farrar, Straus & Giroux"
3,The Wind's Twelve Quarters,Dr. Buffy Walter,Legend,Vintage Books
4,Consider Phlebas,Layla Bauch,Tall tale,Matthias Media
5,Vile Bodies,Donnette Kutch MD,Tall tale,Fairview Press
6,No Country for Old Men,Catina Koepp PhD,Historical fiction,Mandrake of Oxford
7,The Other Side of Silence,Zackary Hirthe IV,Mythopoeia,Black Library
8,Time To Murder And Create,Erasmo Kulas Jr.,Classic,Atlantic Books
9,Look to Windward,Nam Hill,Fantasy,HarperPrism
10,The Violent Bear It Away,Doug Lang,Humor,Adis International
11,Nectar in a Sieve,Mrs. Lyndsay Mante,Textbook,Viking Press
12,For Whom the Bell Tolls,Vernia McKenzie II,Fiction in verse,Brill
13,Tirra Lirra by the River,Eric Hills I,Mystery,Tachyon Publications
14,The Widening Gyre,Iva Durgan,Horror,DAW Books
15,In Death Ground,Dr. Ivey Fahey,Humor,Vintage Books
16,Let Us Now Praise Famous Men,Rogelio Lindgren,Folklore,Athabasca University Press
17,Jesting Pilate,Romona Spencer,Crime/Detective,Faber and Faber
18,As I Lay Dying,Cleveland Considine Sr.,Tall tale,HarperPrism
19,Of Human Bondage,Philomena Halvorson V,Narrative nonfiction,University of Michigan Press
20,No Country for Old Men,Giovanni Kertzmann IV,Fiction in verse,Shire Books

Get different schemas for the same tables

In [26]:
val ordersSchema = DataFrame.getSchemaForSqlTable(dbConfig, "orders")

ordersSchema

id: Int
customerid: Int?
bookid: Int?
date: java.util.Date?
quantity: Int?

In [27]:
val dfOrders = DataFrame.readSqlTable(dbConfig, "orders")

dfOrders.schema()

id: Int
customerid: Int
bookid: Int
date: java.util.Date
quantity: Int

In [28]:
val customersSchema = DataFrame.getSchemaForSqlTable(dbConfig, "customers")

customersSchema

id: Int
firstname: String?
lastname: String?
address: String?
email: String?

In [29]:
customers.schema()

id: Int
firstname: String
lastname: String
address: String
email: String

Schema reading for all non-system tables

In [30]:
val schemas = DataFrame.getSchemaForAllSqlTables(dbConfig)

schemas.keys

[books, customers, orders]

In [31]:
schemas["customers"]

id: Int
firstname: String?
lastname: String?
address: String?
email: String?